version: "3.8"

services:
  db:
    image: postgres:15
    container_name: proofpoint-db
    environment:
      POSTGRES_DB: proofpoint
      POSTGRES_USER: proofpoint
      POSTGRES_PASSWORD: UgQp4XEDDFsbpRZYkhEEdMXP
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - proofpoint-network

  app:
    image: ghcr.io/faisalnh/proofpoint-dashboard:latest
    container_name: proofpoint-app
    ports:
      - "3060:3000"
    environment:
      - DATABASE_URL=postgresql://proofpoint:UgQp4XEDDFsbpRZYkhEEdMXP@db:5432/proofpoint
      - NODE_ENV=production
      - NEXTAUTH_URL=http://172.16.0.189:3060
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - proofpoint-network

volumes:
  postgres_data:

networks:
  proofpoint-network:
    driver: bridge
